CC = gcc
CFLAGS	 = -Wall

# Run ./test.out *floating point number* *floating point number* *floating point number* ...
# You can also run ./test < test.in
# (that doesn't seem to work yet though.)

all:
	$(CC) $(CFLAGS) a1.c -o test.out